### ISSUE TITLE
Create the data model - Error scaffolding db - Could not load file or assembly Bricelam.EntityFrameworkCore.Pluralizer

### ISSUE THREAD

**Issue by KannanRams** [Breeze/northwind-demo#1]
I am getting below error while scaffolding db.

System.IO.FileNotFoundException: Could not load file or assembly 'Bricelam.EntityFrameworkCore.Pluralizer, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Bricelam.EntityFrameworkCore.Pluralizer, Culture=neutral, PublicKeyToken=null'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)

Could not load file or assembly 'Bricelam.EntityFrameworkCore.Pluralizer, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Thanks for your assistance.

**Comment by KannanRams** [comment]
After removing below lines form csproj file, it worked

      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>

**Comment by Byron2016** [comment]
But, I would like to understand why after to erase that lines the problem was solved.
